# Generated by Django 4.2.7 on 2024-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_user_email_confirm_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
    ]
